apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: miniflux-postgresql
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: postgresql
  version: "14.0.5"
  targetNamespace: miniflux
  valuesContent: |-
