# See https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md

nfs:
  server: gmk.local.kakkun61.com
  path: /mnt/usb-raid/kubernetes
