apiVersion: v1
kind: Namespace
metadata:
  name: pdfding
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pdfding
  namespace: kube-system
spec:
  repo: https://charts.pdfding.com/
  chart: pdfding
  version: "0.2.9"
  targetNamespace: pdfding
  valuesContent: |-
